/**
 * Generates a diagnostic SQL query that checks, against the LIVE Supabase
 * project, which migrations in supabase/migrations/ have actually been run
 * there.
 *
 * Why this exists: the Supabase MCP available to Claude sessions in this
 * repo is read-only (root CLAUDE.md), and migrations are applied by a human
 * pasting SQL into the dashboard's SQL editor by hand - there is no
 * migration-runner ledger anywhere recording what has and hasn't been
 * applied. "Which migrations do I still need to run?" has historically been
 * answered by guessing. This answers it by asking the database directly.
 *
 * For each migration file, picks ONE representative object it introduces
 * (a table, a function, or a column added via ALTER TABLE) and emits one
 * `exists_live` check for it. It does not try to verify every statement in
 * every file - one marker per migration is enough to place the boundary
 * between "applied" and "not applied", since migrations run in order.
 * Migrations with no single clean marker (pure RLS/policy files, data-only
 * migrations) are skipped; the gap they leave is at most one or two files
 * and adjacent markers bound it tightly enough to resolve by eye.
 *
 * Usage:
 *   node supabase/tests/migration_status.mjs ../migrations > /tmp/check.sql
 * Paste the output into the Supabase SQL editor. Read top to bottom: the
 * first `exists_live = false` row is the first migration not yet run -
 * run that file and everything after it, in order.
 */
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const DIR = process.argv[2];
if (!DIR) {
  console.error("usage: node migration_status.mjs <migrations-dir>");
  process.exit(1);
}

function markerFor(sql) {
  const table = sql.match(/create table if not exists\s+(\w+)/i);
  if (table) {
    return { kind: "table", label: `table ${table[1]}`, check: `to_regclass('public.${table[1]}') is not null` };
  }

  const fn = sql.match(/create (?:or replace )?function public\.(\w+)/i);
  if (fn) {
    return {
      kind: "function",
      label: `function ${fn[1]}`,
      check: `exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='${fn[1]}')`,
    };
  }

  // Multi-line tolerant: `alter table X ... add column if not exists Y`
  const col = sql.match(/alter table\s+(\w+)[\s\S]*?add column if not exists\s+(\w+)/i);
  if (col) {
    const [, tbl, column] = col;
    return {
      kind: "column",
      label: `column ${tbl}.${column}`,
      check: `exists(select 1 from information_schema.columns where table_name='${tbl}' and column_name='${column}')`,
    };
  }

  return null;
}

const files = readdirSync(DIR).filter((f) => f.endsWith(".sql")).sort();
const rows = [];
for (const f of files) {
  const num = f.match(/^(\d+)/)?.[1];
  if (!num) continue;
  const marker = markerFor(readFileSync(join(DIR, f), "utf8"));
  if (!marker) continue; // no single clean marker - skip, adjacent rows bound the gap
  rows.push({ num, ...marker });
}

const lines = rows.map(
  (r, i) => `  ('${r.num}', '${r.label.replace(/'/g, "''")}', ${r.check})${i < rows.length - 1 ? "," : ""}`,
);

console.log(`-- Generated by supabase/tests/migration_status.mjs - do not hand-edit.
-- Paste into the Supabase SQL editor. Checks one marker object per
-- migration. Read top to bottom: the first "false" row is the first
-- migration you have NOT run. Run that file and everything after it, in
-- filename order.
select migration, marker, exists_live from (values
${lines.join("\n")}
) as t(migration, marker, exists_live)
order by migration;`);
