"use client";

import * as React from "react";
import { createPortal } from "react-dom";
import { getSetting } from "@summit/settings";

/**
 * General "Export to PDF" — one component used by every printable surface
 * (clinical documents, progress reports, assessment dashboards, session
 * notes). Renders the content onto an organization letterhead and prints via
 * the browser's PDF engine, so nothing leaves the machine. Letterhead,
 * credentials and the confidentiality footer come from the central settings.
 */
export function PdfExport({ title, subtitle, children }: {
  title: string;
  subtitle?: string;
  children: React.ReactNode;
}) {
  const [mounted, setMounted] = React.useState(false);
  const sheetRef = React.useRef<HTMLDivElement | null>(null);
  React.useEffect(() => setMounted(true), []);

  // Several export buttons can coexist on a page (e.g. one per session note);
  // only the sheet belonging to the clicked button becomes print-active.
  const doPrint = () => {
    document.body.classList.add("print-mode");
    sheetRef.current?.classList.add("print-active");
    const cleanup = () => {
      document.body.classList.remove("print-mode");
      sheetRef.current?.classList.remove("print-active");
      window.removeEventListener("afterprint", cleanup);
    };
    window.addEventListener("afterprint", cleanup);
    window.print();
    // Safari can skip afterprint; clear on next tick regardless.
    setTimeout(cleanup, 1000);
  };

  const orgName = String(getSetting("org.name"));
  const credentials = String(getSetting("profile.credentials"));
  const preferredName = String(getSetting("profile.preferredName"));
  const showLogo = getSetting("reports.logo") === true;
  const confidential = getSetting("reports.confidentialityFooter") === true;
  const showCredentials = getSetting("reports.credentials") === true;

  return (
    <>
      <button className="btn secondary" onClick={doPrint} aria-label={`Export ${title} to PDF`}>
        ⤓ Export to PDF
      </button>
      {mounted
        ? createPortal(
            <div className="print-sheet" aria-hidden="true" ref={sheetRef}>
              <header className="ps-head">
                {showLogo ? <span className="ps-mark" /> : null}
                <div>
                  <div className="ps-org">{orgName}</div>
                  <div className="ps-doc">{title}</div>
                  {subtitle ? <div className="ps-sub">{subtitle}</div> : null}
                </div>
                <div className="ps-date">{new Date().toISOString().slice(0, 10)}</div>
              </header>
              <main className="ps-body">{children}</main>
              <footer className="ps-foot">
                {showCredentials && (preferredName || credentials) ? (
                  <span>Prepared by {preferredName || "the assigned clinician"}{credentials ? `, ${credentials}` : ""} · </span>
                ) : null}
                {confidential ? (
                  <span>
                    Confidential clinical record — intended only for the client, their circle of care and authorized staff.
                    Generated by Summit; the signed record in the platform remains authoritative.
                  </span>
                ) : null}
              </footer>
            </div>,
            document.body,
          )
        : null}
    </>
  );
}

/** Simple labelled section for print sheets. */
export function PrintSection({ heading, text }: { heading: string; text: string }) {
  if (!text.trim()) return null;
  return (
    <section className="ps-section">
      <h2>{heading}</h2>
      {text.split("\n").filter(Boolean).map((line, i) => <p key={i}>{line}</p>)}
    </section>
  );
}
