/**
 * Course catalogue.
 *
 * IMPORTANT (compliance): `certificate` and `ceu` are only shown as available
 * when a course's status is verified. The `verifiedStatus` flag gates that
 * display in the UI.
 */
export type CourseLevel = "Awareness" | "Foundational" | "Intermediate" | "Advanced";
export type Delivery = "Self-paced" | "Live virtual" | "On-site" | "Blended";
export type AcademySlug = "student" | "parent" | "teacher" | "clinical" | "digital";

export type Course = {
  slug: string;
  title: string;
  demo: true;
  academy: AcademySlug;
  audience: string;
  level: CourseLevel;
  topic: string;
  delivery: Delivery;
  durationHours: number;
  languages: string[]; // language codes
  summary: string;
  objectives: string[];
  modules: string[];
  prerequisites: string;
  instructor: string;
  price: number | "Institutional" | "Free";
  certificate: boolean;
  ceu: boolean;
  verifiedStatus: boolean; // whether certificate/CEU claims are verified
  institutionalOnly: boolean;
  region: "Global" | "Europe" | "Caribbean" | "North America";
};

const baseModules = (title: string) => [
  `Welcome & orientation`,
  `Core concepts of ${title.toLowerCase()}`,
  `Strategies in practice`,
  `Scenario-based application`,
  `Data & progress monitoring`,
  `Knowledge check & wrap-up`,
];

export const courses: Course[] = [
  {
    slug: "behaviour-is-communication",
    title: "Behaviour Is Communication",
    demo: true,
    academy: "teacher",
    audience: "Educators, EAs, caregivers",
    level: "Awareness",
    topic: "Foundations",
    delivery: "Self-paced",
    durationHours: 2,
    languages: ["en", "fr", "es"],
    summary:
      "Understand behaviour as communication and learn to read the function behind what students do.",
    objectives: [
      "Describe behaviour as a form of communication",
      "Identify common functions of behaviour",
      "Respond in ways that teach rather than escalate",
    ],
    modules: baseModules("behaviour as communication"),
    prerequisites: "None",
    instructor: "MEGBA Faculty",
    price: "Free",
    certificate: true,
    ceu: false,
    verifiedStatus: true,
    institutionalOnly: false,
    region: "Global",
  },
  {
    slug: "foundations-of-classroom-behaviour-support",
    title: "Foundations of Classroom Behaviour Support",
    demo: true,
    academy: "teacher",
    audience: "Teachers and learning-support staff",
    level: "Foundational",
    topic: "Classroom support",
    delivery: "Blended",
    durationHours: 6,
    languages: ["en", "fr", "de", "pl"],
    summary:
      "Build predictable, inclusive classrooms using prevention, reinforcement, and clear routines.",
    objectives: [
      "Set up antecedent strategies that prevent challenging behaviour",
      "Use reinforcement effectively and ethically",
      "Establish routines that support all learners",
    ],
    modules: baseModules("classroom behaviour support"),
    prerequisites: "None",
    instructor: "MEGBA Faculty",
    price: 149,
    certificate: true,
    ceu: false,
    verifiedStatus: true,
    institutionalOnly: false,
    region: "Global",
  },
  {
    slug: "reinforcement-in-everyday-teaching",
    title: "Reinforcement in Everyday Teaching",
    demo: true,
    academy: "teacher",
    audience: "Educators",
    level: "Foundational",
    topic: "Reinforcement",
    delivery: "Self-paced",
    durationHours: 3,
    languages: ["en", "es", "pt"],
    summary: "Make reinforcement practical, respectful, and sustainable in a real classroom.",
    objectives: [
      "Distinguish reinforcement from bribery",
      "Design feasible reinforcement systems",
      "Fade supports toward independence",
    ],
    modules: baseModules("reinforcement"),
    prerequisites: "None",
    instructor: "MEGBA Faculty",
    price: 99,
    certificate: true,
    ceu: false,
    verifiedStatus: true,
    institutionalOnly: false,
    region: "Global",
  },
  {
    slug: "functional-behaviour-assessment-fundamentals",
    title: "Functional Behaviour Assessment Fundamentals",
    demo: true,
    academy: "clinical",
    audience: "Educators, analysts, allied health",
    level: "Intermediate",
    topic: "Assessment",
    delivery: "Live virtual",
    durationHours: 8,
    languages: ["en", "fr"],
    summary: "Learn the logic and practice of functional behaviour assessment in school contexts.",
    objectives: [
      "Explain the purpose of an FBA",
      "Gather and interpret ABC data",
      "Link function to intervention",
    ],
    modules: baseModules("functional behaviour assessment"),
    prerequisites: "Foundations of Classroom Behaviour Support (recommended)",
    instructor: "MEGBA Faculty",
    price: 249,
    certificate: true,
    ceu: true,
    verifiedStatus: false,
    institutionalOnly: false,
    region: "Global",
  },
  {
    slug: "parent-coaching-foundations",
    title: "Parent Coaching Foundations",
    demo: true,
    academy: "parent",
    audience: "Parents and caregivers",
    level: "Foundational",
    topic: "Parenting",
    delivery: "Live virtual",
    durationHours: 4,
    languages: ["en", "es", "it", "ro"],
    summary: "Practical, jargon-free strategies caregivers can use at home from day one.",
    objectives: [
      "Understand why behaviour happens",
      "Build routines that reduce conflict",
      "Support communication and independence",
    ],
    modules: baseModules("parent coaching"),
    prerequisites: "None",
    instructor: "MEGBA Faculty",
    price: "Free",
    certificate: false,
    ceu: false,
    verifiedStatus: true,
    institutionalOnly: false,
    region: "Global",
  },
  {
    slug: "supporting-emotional-regulation",
    title: "Supporting Emotional Regulation",
    demo: true,
    academy: "student",
    audience: "Educators and families",
    level: "Foundational",
    topic: "Regulation",
    delivery: "Self-paced",
    durationHours: 3,
    languages: ["en", "fr", "bg", "cs"],
    summary: "Help children recognize, name, and manage big feelings with supportive strategies.",
    objectives: [
      "Model and teach regulation strategies",
      "Design calm, predictable environments",
      "Coach children through dysregulation",
    ],
    modules: baseModules("emotional regulation"),
    prerequisites: "None",
    instructor: "MEGBA Faculty",
    price: 79,
    certificate: true,
    ceu: false,
    verifiedStatus: true,
    institutionalOnly: false,
    region: "Global",
  },
  {
    slug: "introduction-to-ndbi",
    title: "Introduction to Naturalistic Developmental Behavioural Interventions",
    demo: true,
    academy: "clinical",
    audience: "Analysts, technicians, early-years staff",
    level: "Intermediate",
    topic: "Early intervention",
    delivery: "Blended",
    durationHours: 6,
    languages: ["en"],
    summary: "An overview of NDBI principles and their application in naturalistic settings.",
    objectives: [
      "Describe core NDBI principles",
      "Embed learning opportunities in play and routines",
      "Collaborate with families and teams",
    ],
    modules: baseModules("NDBI"),
    prerequisites: "Behaviour foundations recommended",
    instructor: "MEGBA Faculty",
    price: 199,
    certificate: true,
    ceu: true,
    verifiedStatus: false,
    institutionalOnly: false,
    region: "Global",
  },
  {
    slug: "pecs-awareness-for-educational-teams",
    title: "PECS Awareness for Educational Teams",
    demo: true,
    academy: "teacher",
    audience: "Educational teams",
    level: "Awareness",
    topic: "Communication",
    delivery: "Self-paced",
    durationHours: 2,
    languages: ["en", "fr"],
    summary:
      "An awareness-level introduction to the Picture Exchange Communication System for school teams.",
    objectives: [
      "Understand what PECS is and is not",
      "Recognize when specialist involvement is needed",
      "Support consistent implementation",
    ],
    modules: baseModules("PECS awareness"),
    prerequisites: "None",
    instructor: "MEGBA Faculty",
    price: 89,
    certificate: false,
    ceu: false,
    verifiedStatus: true,
    institutionalOnly: false,
    region: "Global",
  },
  {
    slug: "esdm-informed-early-learning-strategies",
    title: "ESDM-Informed Early Learning Strategies",
    demo: true,
    academy: "clinical",
    audience: "Early-years teams",
    level: "Intermediate",
    topic: "Early intervention",
    delivery: "Live virtual",
    durationHours: 5,
    languages: ["en"],
    summary: "Strategies informed by the Early Start Denver Model for early-learning environments.",
    objectives: [
      "Describe ESDM-informed principles",
      "Embed goals into everyday activities",
      "Track early developmental progress",
    ],
    modules: baseModules("ESDM-informed strategies"),
    prerequisites: "Early intervention basics recommended",
    instructor: "MEGBA Faculty",
    price: 219,
    certificate: true,
    ceu: false,
    verifiedStatus: false,
    institutionalOnly: false,
    region: "Global",
  },
  {
    slug: "triple-p-informed-positive-parenting",
    title: "Triple P-Informed Positive Parenting Principles",
    demo: true,
    academy: "parent",
    audience: "Parents and caregivers",
    level: "Foundational",
    topic: "Parenting",
    delivery: "Self-paced",
    durationHours: 4,
    languages: ["en", "es"],
    summary: "Positive-parenting principles informed by the Triple P framework.",
    objectives: [
      "Apply positive-parenting principles at home",
      "Encourage desirable behaviour",
      "Manage everyday challenges calmly",
    ],
    modules: baseModules("positive parenting"),
    prerequisites: "None",
    instructor: "MEGBA Faculty",
    price: 129,
    certificate: true,
    ceu: false,
    verifiedStatus: false,
    institutionalOnly: false,
    region: "Global",
  },
  {
    slug: "ethical-behaviour-support-in-schools",
    title: "Ethical Behaviour Support in Schools",
    demo: true,
    academy: "clinical",
    audience: "Educators and professionals",
    level: "Intermediate",
    topic: "Ethics",
    delivery: "Self-paced",
    durationHours: 3,
    languages: ["en", "fr", "de"],
    summary: "Navigate consent, dignity, and least-restrictive practice in school settings.",
    objectives: [
      "Apply ethical decision-making frameworks",
      "Centre dignity and assent",
      "Choose least-restrictive supports",
    ],
    modules: baseModules("ethical behaviour support"),
    prerequisites: "None",
    instructor: "MEGBA Faculty",
    price: 119,
    certificate: true,
    ceu: true,
    verifiedStatus: false,
    institutionalOnly: false,
    region: "Global",
  },
  {
    slug: "behaviour-skills-training-for-supervisors",
    title: "Behaviour Skills Training for Supervisors",
    demo: true,
    academy: "clinical",
    audience: "Supervisors and training managers",
    level: "Advanced",
    topic: "Supervision",
    delivery: "Live virtual",
    durationHours: 6,
    languages: ["en"],
    summary: "Use Behaviour Skills Training (BST) to build and coach staff competencies.",
    objectives: [
      "Apply the BST model (instruct, model, rehearse, feedback)",
      "Design competency checklists",
      "Give effective performance feedback",
    ],
    modules: baseModules("behaviour skills training"),
    prerequisites: "Supervisory role recommended",
    instructor: "MEGBA Faculty",
    price: "Institutional",
    certificate: true,
    ceu: true,
    verifiedStatus: false,
    institutionalOnly: true,
    region: "Global",
  },
  {
    slug: "technician-foundations",
    title: "Technician Foundations",
    demo: true,
    academy: "clinical",
    audience: "Aspiring behaviour technicians",
    level: "Foundational",
    topic: "Technician training",
    delivery: "Self-paced",
    durationHours: 12,
    languages: ["en", "es", "ro", "pl"],
    summary: "Foundational competencies for behaviour technicians and support staff.",
    objectives: [
      "Understand measurement and data collection",
      "Support skill-acquisition and behaviour-reduction plans",
      "Document and communicate professionally",
    ],
    modules: baseModules("technician foundations"),
    prerequisites: "None",
    instructor: "MEGBA Faculty",
    price: 299,
    certificate: true,
    ceu: false,
    verifiedStatus: true,
    institutionalOnly: false,
    region: "Global",
  },
  {
    slug: "international-school-behaviour-consultation",
    title: "International School Behaviour Consultation",
    demo: true,
    academy: "clinical",
    audience: "Consultants and school leaders",
    level: "Advanced",
    topic: "Consultation",
    delivery: "Live virtual",
    durationHours: 8,
    languages: ["en"],
    summary: "A framework for delivering behaviour consultation across cultures and curricula.",
    objectives: [
      "Adapt recommendations to local context",
      "Build sustainable school-wide systems",
      "Coach staff toward independence",
    ],
    modules: baseModules("international consultation"),
    prerequisites: "Consultation experience recommended",
    instructor: "MEGBA Faculty",
    price: "Institutional",
    certificate: true,
    ceu: true,
    verifiedStatus: false,
    institutionalOnly: true,
    region: "Global",
  },
  {
    slug: "culturally-responsive-behaviour-support",
    title: "Culturally Responsive Behaviour Support",
    demo: true,
    academy: "teacher",
    audience: "Educators and professionals",
    level: "Intermediate",
    topic: "Inclusion",
    delivery: "Self-paced",
    durationHours: 3,
    languages: ["en", "fr", "es", "pt"],
    summary: "Centre culture, context, and family voice in behaviour support.",
    objectives: [
      "Recognize cultural bias in behaviour judgements",
      "Partner respectfully with families",
      "Adapt supports to context",
    ],
    modules: baseModules("culturally responsive support"),
    prerequisites: "None",
    instructor: "MEGBA Faculty",
    price: 99,
    certificate: true,
    ceu: false,
    verifiedStatus: true,
    institutionalOnly: false,
    region: "Global",
  },
  {
    slug: "data-collection-for-busy-classrooms",
    title: "Data Collection for Busy Classrooms",
    demo: true,
    academy: "teacher",
    audience: "Teachers and EAs",
    level: "Foundational",
    topic: "Data",
    delivery: "Self-paced",
    durationHours: 2,
    languages: ["en", "fr", "cs", "bg"],
    summary: "Simple, sustainable ways to collect classroom data that actually gets used.",
    objectives: [
      "Choose feasible data-collection methods",
      "Turn data into decisions",
      "Avoid common measurement pitfalls",
    ],
    modules: baseModules("classroom data"),
    prerequisites: "None",
    instructor: "MEGBA Faculty",
    price: 69,
    certificate: true,
    ceu: false,
    verifiedStatus: true,
    institutionalOnly: false,
    region: "Global",
  },
];

export const getCourse = (slug: string) => courses.find((c) => c.slug === slug);

export const courseTopics = Array.from(new Set(courses.map((c) => c.topic))).sort();
export const courseLevels: CourseLevel[] = ["Awareness", "Foundational", "Intermediate", "Advanced"];
export const deliveryMethods: Delivery[] = ["Self-paced", "Live virtual", "On-site", "Blended"];
